include:
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.3/gitlab-base.yml'
    ref: $CI_BRANCH_REF
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.3/gitlab-host-qwt.yml'
    ref: $CI_BRANCH_REF
